/// Types of AI-generated insights
enum InsightType {
  observation, // Pattern noticed
  suggestion, // Actionable recommendation
  encouragement, // Positive reinforcement
  reflection, // Deeper question to consider
}

/// An insight generated by the AI
class AIInsight {
  final String id;
  final String content;
  final InsightType type;
  final DateTime createdAt;
  final List<String> relatedEntryIds;
  final List<String> themes;
  final bool isDismissed;

  const AIInsight({
    required this.id,
    required this.content,
    required this.type,
    required this.createdAt,
    this.relatedEntryIds = const [],
    this.themes = const [],
    this.isDismissed = false,
  });

  AIInsight copyWith({
    String? content,
    InsightType? type,
    List<String>? relatedEntryIds,
    List<String>? themes,
    bool? isDismissed,
  }) {
    return AIInsight(
      id: id,
      content: content ?? this.content,
      type: type ?? this.type,
      createdAt: createdAt,
      relatedEntryIds: relatedEntryIds ?? this.relatedEntryIds,
      themes: themes ?? this.themes,
      isDismissed: isDismissed ?? this.isDismissed,
    );
  }

  /// Icon for this insight type
  String get iconName {
    switch (type) {
      case InsightType.observation:
        return 'visibility';
      case InsightType.suggestion:
        return 'lightbulb';
      case InsightType.encouragement:
        return 'favorite';
      case InsightType.reflection:
        return 'psychology';
    }
  }

  /// Label for this insight type
  String get typeLabel {
    switch (type) {
      case InsightType.observation:
        return 'Pattern';
      case InsightType.suggestion:
        return 'Suggestion';
      case InsightType.encouragement:
        return 'Encouragement';
      case InsightType.reflection:
        return 'Reflection';
    }
  }
}

/// Themes that AI can detect in journal entries
class JournalTheme {
  static const String stress = 'stress';
  static const String motivation = 'motivation';
  static const String fatigue = 'fatigue';
  static const String positivity = 'positivity';
  static const String anxiety = 'anxiety';
  static const String gratitude = 'gratitude';
  static const String relationships = 'relationships';
  static const String work = 'work';
  static const String selfCare = 'self-care';
  static const String growth = 'growth';

  static const List<String> all = [
    stress,
    motivation,
    fatigue,
    positivity,
    anxiety,
    gratitude,
    relationships,
    work,
    selfCare,
    growth,
  ];

  static String getLabel(String theme) {
    switch (theme) {
      case stress:
        return 'Stress';
      case motivation:
        return 'Motivation';
      case fatigue:
        return 'Fatigue';
      case positivity:
        return 'Positivity';
      case anxiety:
        return 'Anxiety';
      case gratitude:
        return 'Gratitude';
      case relationships:
        return 'Relationships';
      case work:
        return 'Work';
      case selfCare:
        return 'Self-Care';
      case growth:
        return 'Growth';
      default:
        return theme;
    }
  }
}
